fix: Added mysql to static-analysis CI workflow

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -13,6 +13,16 @@ jobs:
   static-analysis:
     name: Static Analysis (PHP ${{ matrix.php-versions }})
     runs-on: ubuntu-latest
+    services:
+      mysql:
+        image: mysql:latest
+        env:
+          MYSQL_ALLOW_EMPTY_PASSWORD: false
+          MYSQL_ROOT_PASSWORD: symfony
+          MYSQL_DATABASE: symfony
+        ports:
+          - 3306/tcp
+        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
     strategy:
       fail-fast: true
       matrix:
@@ -28,14 +38,14 @@ jobs:
 
       - name: Validate main `composer.json` and `composer.lock` files
         run: composer validate --no-check-version
-        
+
       - name: Check if any dependencies are compromised
         if: always() && steps.install.outcome == 'success'
         run: composer audit
 
       - name: Composer Dependencies
         uses: "ramsey/composer-install@v2"
-        
+
       - name: Lint YAML files
         if: always() && steps.install.outcome == 'success'
         run: ./bin/console lint:yaml config --parse-tags
@@ -55,7 +65,12 @@ jobs:
       - name: Lint Doctrine entities
         if: always() && steps.install.outcome == 'success'
         run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
-        
+
+      - name: Run Migration
+        run: php bin/console doctrine:schema:create || echo "No schema found or schema failed"
+        env:
+          DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
+
       - name: Analyse PHP Code (PHPStan)
         run: vendor/bin/phpstan analyse
 
